- owa/=3.0.0
- owa/app/css/openmrs-owa-idgen.css
- owa/app/index.html
- owa/app/js/components/App.jsx
- owa/app/js/components/bodyLayout.jsx
- owa/app/js/components/common/header.jsx
- owa/app/js/utilities/apiHelper.js
- owa/package-lock.json
- owa/package.json
[IDGEN-61  Add Navigation](https://issues.openmrs.org/browse/IDGEN-61)
Adds the logout, location and account navs on the nav bar. adds also the three tabs for Manage Patient Identifier Sources, Auto-Generation Options and View Log Entries.
>  IDGEN-61  Add Navigation

- owa/app/js/components/bodyLayout.jsx
- owa/app/js/components/manage_patient_identifier_sources/configureSource.jsx
- owa/app/js/components/manage_patient_identifier_sources/existingIdentifierSources.jsx
- owa/app/js/components/manage_patient_identifier_sources/managePatientIdentifierSources.css
- owa/app/js/components/manage_patient_identifier_sources/managePatientIdentifierSources.jsx
- owa/app/js/components/manage_patient_identifier_sources/newPatientIdentifierSources.jsx
- owa/app/js/components/manage_patient_identifier_sources/new_patient_identifier_sources/localIdentifierGenerator.jsx
- owa/app/js/components/manage_patient_identifier_sources/new_patient_identifier_sources/localPoolIdentifiers.jsx
- owa/app/js/components/manage_patient_identifier_sources/new_patient_identifier_sources/newPatientIdentifierSources.css
- owa/app/js/components/manage_patient_identifier_sources/new_patient_identifier_sources/remoteIdentifierSource.jsx
- owa/app/js/components/manage_patient_identifier_sources/viewSource.jsx
[IDGEN-54 Manage Identifier Sources UI Redesign](https://issues.openmrs.org/browse/IDGEN-54)
Creates a new ui for the Manage Identifier Sources using ReactJS, HTML and CSS.
> IDGEN-54 Manage Identifier Sources UI Redesign

- omod/pom.xml
- omod/src/main/java/org/openmrs/module/idgen/web/controller/IdgenRestController.java
- omod/src/main/resources/config.xml
[IDGEN-62 Set up module for REST web services calls](https://issues.openmrs.org/browse/IDGEN-62)
Make the module ready for REST calls.
> IDGEN-62 Set up module for REST webservices calls

- owa/app/js/components/bodyLayout.jsx
- owa/app/js/components/manage_autogeneration_option/ManageAutoGenerationOption.jsx
- owa/app/js/components/manage_autogeneration_option/css/manage-autogeneration.css
- owa/package-lock.json
[IDGEN-55](https://issues.openmrs.org/browse/IDGEN-55) Manage Autogeneration Option UI Redesign
Aim is to create a user-friendly user interface for the Manage Autogeneration Option page with reactJs
> IDGEN-55 Manage Autogeneration Option UI Redesign

- owa/app/css/openmrs-owa-idgen.css
- owa/app/js/components/breadcrumbs/breadcrumbs.css
- owa/app/js/components/breadcrumbs/breadcrumbs.jsx
- owa/app/js/components/common/header.jsx
[IDGEN-64 Add breadcrumbs](https://issues.openmrs.org/browse/IDGEN-64)
Add breadcrumbs to the project to ease navigation, and allow users to keep track of their locations within program
> IDGEN-64  Add breadcrumbs

- .gitignore
- api/src/main/java/org/openmrs/module/idgen/AutoGenerationOption.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/AutoGenerationOptionResource.java
- omod/src/test/java/org/openmrs/module/idgen/rest/controller/AutoGenerationOptionControllerTest.java
- omod/src/test/java/org/openmrs/module/idgen/rest/resource/AutoGenerationOptionResourceTest.java
[[IDGEN-71] Create AutoGenerartionOption restful API endpoints](https://issues.openmrs.org/browse/IDGEN-71)
Create API endpoints for AutoGenerationOption that enables one to perform CRUD functionality
> [IDGEN-71] Create AutoGenerartionOption restful API endpoints

- owa/app/js/components/App.jsx
- owa/app/js/components/manage_autogeneration_option/ManageAutoGenerationOption.jsx
- owa/app/js/components/manage_autogeneration_option/css/manage-autogeneration.css
- owa/package-lock.json
- owa/package.json
- owa/webpack.config.js
[IDGEN-79 Link Auto Generation Options EndPoints to OWA](https://issues.openmrs.org/browse/IDGEN-79)
Link Auto Generation Options EndPoints to OWA
> IDGEN-79 Link Auto Generation Options EndPoints to OWA

- owa/app/js/components/manage_autogeneration_option/ManageAutoGenerationOption.jsx
[IDGEN-79 Follow up](https://issues.openmrs.org/browse/IDGEN-79)
Remove unused search input from Options page
> IDGEN-79 follow-up

- owa/app/js/components/common/header.jsx
[IDGEN-101 Link Log Entries EndPoints to OWA](https://issues.openmrs.org/browse/IDGEN-101)
Link 'My Account' in navbar to user's account page
> IDGEN-101 Link 'My Account' in navbar to user's account page

- owa/app/css/openmrs-owa-idgen.css
- owa/app/js/components/App.jsx
- owa/app/js/components/bodyLayout.jsx
- owa/app/js/components/breadcrumbs/breadcrumbs.css
- owa/app/js/components/breadcrumbs/breadcrumbs.jsx
[IDGEN-102 Link Log Entries EndPoints to OWA](https://issues.openmrs.org/browse/IDGEN-102)
Update IDGEN Breadcrumbs to show active tab
> [IDGEN-102] Update IDGEN Breadcrumbs to show active tab

- owa/app/js/components/common/header.jsx
[[IDGEN-100] Auto-hide location dropdown in navbar after click](https://issues.openmrs.org/browse/IDGEN-100)
Location dropdown should auto-hide after a location on the dropdown is selected
> [IDGEN-100] Auto-hide location dropdown in navbar after click

- owa/app/js/components/manage_patient_identifier_sources/new_patient_identifier_sources/localPoolIdentifiers.jsx
- owa/app/js/components/manage_patient_identifier_sources/view_patient_identifier_sources/localIdentifierGenerator.jsx
- owa/app/js/components/manage_patient_identifier_sources/view_patient_identifier_sources/localPoolIdentifiers.jsx
- owa/app/js/utilities/toast.js
[IDGEN-103: Fix bugs in the Manage Patient Identifier Sources OWA](https://issues.openmrs.org/browse/IDGEN-103)
Fixes validation errors from [IDGEN-80](https://issues.openmrs.org/browse/IDGEN-80) including:
- Correct format of uploaded identifiers.
- Consistent Toast error messages.
- Displays the correct format of the data to be uploaded.
> Fix bugs in the Manage Patient Identifier Sources OWA

- owa/app/js/components/view_log_entries/viewLogEntries.jsx
[IDGEN-105 Link Log Entries EndPoints to OWA](https://issues.openmrs.org/browse/IDGEN-105)
* Enable searching by source and generatedBy on first load
* Make source and generatedBy values to update when user input is changed
* URLifiy user inputs in the search form
* Return '_correct_' log entries when some of the search form values are not provided
* Fix '_filter_' error when there are log entries with no comments
* Change data displayed in generatedBy column to generatedBy.display from generatedBy.username
> IDGEN 105 Fix Bugs in View Log Entries OWA

- api/src/main/java/org/openmrs/module/idgen/service/BaseIdentifierSourceService.java
- api/src/main/java/org/openmrs/module/idgen/service/IdentifierSourceService.java
- api/src/main/java/org/openmrs/module/idgen/service/db/HibernateIdentifierSourceDAO.java
- api/src/main/java/org/openmrs/module/idgen/service/db/IdentifierSourceDAO.java
- api/src/test/java/org/openmrs/module/idgen/service/IdentifierSourceServiceTest.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/IdentifierSourceResource.java
- omod/src/test/java/org/openmrs/module/idgen/rest/resource/IdentifierSourceResourceTest.java
- omod/src/test/java/org/openmrs/module/idgen/web/controller/IdentifierSourceRestControllerTest.java
[IDGEN-98: Fix bugs in the Identifier Source Resource](https://issues.openmrs.org/browse/IDGEN-98)
Fixes the following bugs / issues that were created in [IDGEN-65](https://issues.openmrs.org/browse/IDGEN-65):
- Upload of reserved identifiers.
- Upload of identifiers from file.
- Upload of batch identifiers from source.
- Export of identifiers.
> Fix bugs in the Identifier Source Resource

- omod/src/test/java/org/openmrs/module/idgen/web/controller/IdentifierSourceRestControllerTest.java
[IDGEN-109: Fix errors in Identifier Source Rest Controller Test](https://issues.openmrs.org/browse/IDGEN-109)
Fix errors in Identifier Source Rest Controller Test
> Fix errors in Identifier Source Rest Controller Test

- owa/app/js/components/manage_patient_identifier_sources/edit_patient_identifier_sources/localIdentifierGenerator.jsx
- owa/app/js/components/manage_patient_identifier_sources/edit_patient_identifier_sources/localPoolIdentifiers.jsx
- owa/app/js/components/manage_patient_identifier_sources/edit_patient_identifier_sources/remoteIdentifierSource.jsx
- owa/app/js/components/manage_patient_identifier_sources/existingIdentifierSources.jsx
- owa/app/js/components/manage_patient_identifier_sources/new_patient_identifier_sources/localIdentifierGenerator.jsx
- owa/app/js/components/manage_patient_identifier_sources/new_patient_identifier_sources/localPoolIdentifiers.jsx
- owa/app/js/components/manage_patient_identifier_sources/new_patient_identifier_sources/remoteIdentifierSource.jsx
- owa/app/js/components/manage_patient_identifier_sources/view_patient_identifier_sources/localIdentifierGenerator.jsx
- owa/app/js/components/manage_patient_identifier_sources/view_patient_identifier_sources/localPoolIdentifiers.jsx
- owa/app/js/components/manage_patient_identifier_sources/view_patient_identifier_sources/remoteIdentifierSource.jsx
- owa/app/js/components/manage_patient_identifier_sources/view_patient_identifier_sources/viewPatientIdentifierSources.css
[IDGEN-106: Fix errors in manage Identifier sources OWA](https://issues.openmrs.org/browse/IDGEN-106)
Fix errors in manage Identifier sources OWA including:
- Ability to edit pool to remove source
- Users can now view used and available identifiers.
> Fix errors in manage Identifier sources OWA

- api/src/main/java/org/openmrs/module/idgen/AutoGenerationOption.java
- api/src/main/java/org/openmrs/module/idgen/BaseIdentifierSource.java
- api/src/main/java/org/openmrs/module/idgen/Identifier.java
- api/src/main/java/org/openmrs/module/idgen/IdentifierPool.java
- api/src/main/java/org/openmrs/module/idgen/LogEntry.java
- api/src/main/java/org/openmrs/module/idgen/PooledIdentifier.java
- api/src/test/java/org/openmrs/module/idgen/service/IdentifierSourceServiceTest.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/AutoGenerationOptionResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/IdentifierResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/IdentifierSourceResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/LogEntryResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/handler/IdentifierPoolResourceHandler.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/handler/RemoteIdentifierSourceResourceHandler.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/handler/SequentialIdentifierGeneratorResourceHandler.java
- omod/src/main/java/org/openmrs/module/idgen/web/controller/IdgenSubResourceRestController.java
- omod/src/test/java/org/openmrs/module/idgen/rest/controller/IdentifierResourceTest.java
- omod/src/test/java/org/openmrs/module/idgen/rest/resource/handler/IdentifierPoolResourceHandlerTest.java
- omod/src/test/java/org/openmrs/module/idgen/rest/resource/handler/RemoteIdentifierSourceResourceHandlerTest.java
- omod/src/test/java/org/openmrs/module/idgen/rest/resource/handler/SequentialIdentifierGeneratorResourceHandlerTest.java
- omod/src/test/java/org/openmrs/module/idgen/web/controller/IdentifierSourceRestControllerTest.java
Ticket : https://issues.openmrs.org/browse/IDGEN-42
> IDGEN-42: Add webservices to idgen module

- .travis.yml
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/AutoGenerationOptionResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/IdentifierResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/IdentifierSourceResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/LogEntryResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/handler/IdentifierPoolResourceHandler.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/handler/RemoteIdentifierSourceResourceHandler.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/handler/SequentialIdentifierGeneratorResourceHandler.java
**Issue worked on:** https://issues.openmrs.org/browse/IDGEN-111
> IDGEN-111: Support openmrs platform 2.3.x

- omod/src/main/java/org/openmrs/module/idgen/rest/resource/AutoGenerationOptionResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/IdentifierResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/IdentifierSourceResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/LogEntryResource.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/handler/IdentifierPoolResourceHandler.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/handler/RemoteIdentifierSourceResourceHandler.java
- omod/src/main/java/org/openmrs/module/idgen/rest/resource/handler/SequentialIdentifierGeneratorResourceHandler.java
- omod/src/main/java/org/openmrs/module/idgen/rest/search/LogEntrySearchHandler.java
**Issue worked on:** https://issues.openmrs.org/browse/IDGEN-113
> IDGEN-113: Support openmrs platform 2.4.x

- api/src/main/resources/IdentifierSource.hbm.xml
**Description of Changes I Made :**
Mapped the sequences correctly.
**Link to Ticket :** https://issues.openmrs.org/browse/IDGEN-115
> IDGEN-115 Map Sequence Correctly

- api/src/main/resources/liquibase.xml
**Changes I made**
Changes type to boolean where error was coming.
**Link to ticket**
https://issues.openmrs.org/browse/IDGEN-118
> IDGEN-118 Convert tinyint(1) to boolean in liquibase file of IdGen Module

- api/src/main/resources/liquibase.xml
**Changes I made**
Correct the uuid type.
**Link to ticket**
https://issues.openmrs.org/browse/IDGEN-119
> IDGEN-119 UUID error on PostgreSQL with reference meta data module

- api/src/main/resources/liquibase.xml
**Changes I made**
Corrected the older checksums to values before the liquibase update
**Link to ticket**
https://issues.openmrs.org/browse/IDGEN-120
> IDGEN-120 Correct The liquibase checksums for OpenMRS IDGEN module

- api/src/main/java/org/openmrs/module/idgen/service/db/HibernateIdentifierSourceDAO.java
**Changes I made**
Added explicit type info.
**Link to ticket**
https://issues.openmrs.org/browse/IDGEN-121
> IDGEN-121 Error adding new Patient Identifier Source

- pom.xml
> Pointing git to HEAD tag after release

- omod/src/main/java/org/openmrs/module/idgen/rest/resource/SequenceIdentifierResource.java
Added SequenceIdentifierResource.java to get the next OpenMRS Patient Identifier thro' WS. 
JIRA ticket url - https://issues.openmrs.org/browse/IDGEN-124
> IDGEN-124 - Ability to retrieve Patient ID from OpenMRS using WS

- omod/src/main/webapp/viewLogEntries.jsp
@isears:
**Why:**
Possible reflected XSS bugs in the search functionality of the view log entries. Steps to reproduce can be found [here](https://docs.google.com/document/d/1aPeL-PB9Usq2FteIbD_4qfPgPu41UOC9adocS0Gntkw/edit?usp=sharing).
> RA-1865: Patch bugs discovered by NCSU team

- omod/src/main/java/org/openmrs/module/idgen/web/controller/IdentifierSourceController.java
- omod/src/main/java/org/openmrs/module/idgen/web/extension/AdminList.java
- omod/src/main/webapp/localHeader.jsp
Followup commit to the commit here: https://github.com/openmrs/openmrs-module-idgen/commit/0d1df399259e066de394511d5565072f6ce6ca9e
Ticket: https://issues.openmrs.org/browse/LUI-189
> LUI-189: Followup commit to correctly map url suffixes

- api/src/main/java/org/openmrs/module/idgen/SequentialIdentifierGenerator.java
- api/src/main/java/org/openmrs/module/idgen/suffixprovider/ConstantSuffixProvider.java
- api/src/main/java/org/openmrs/module/idgen/suffixprovider/LocationBasedSuffixProvider.java
- api/src/main/java/org/openmrs/module/idgen/suffixprovider/SuffixProvider.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/idgen/SequentialIdentifierGeneratorTest.java
Similar to Prefix providers with this development is possible to provide more complex suffixs for the identifiers.
> Added support for Suffix Providers

- pom.xml
This fixes the issue:  MalformedInputException: Input length = 1
> Add maven-resources-plugin
